// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: message.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Ts            uint64                 `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionedMessage) Reset() {
	*x = VersionedMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionedMessage) ProtoMessage() {}

func (x *VersionedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionedMessage.ProtoReflect.Descriptor instead.
func (*VersionedMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *VersionedMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionedMessage) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *VersionedMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AuthenticationToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationToken) Reset() {
	*x = AuthenticationToken{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationToken) ProtoMessage() {}

func (x *AuthenticationToken) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationToken.ProtoReflect.Descriptor instead.
func (*AuthenticationToken) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GroupChannel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	ChannelType   int32                  `protobuf:"varint,3,opt,name=channelType,proto3" json:"channelType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChannel) Reset() {
	*x = GroupChannel{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChannel) ProtoMessage() {}

func (x *GroupChannel) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChannel.ProtoReflect.Descriptor instead.
func (*GroupChannel) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *GroupChannel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupChannel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupChannel) GetChannelType() int32 {
	if x != nil {
		return x.ChannelType
	}
	return 0
}

type GetGroupMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembers) Reset() {
	*x = GetGroupMembers{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembers) ProtoMessage() {}

func (x *GetGroupMembers) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembers.ProtoReflect.Descriptor instead.
func (*GetGroupMembers) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupMembers) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type GetGroupMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int32                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Before        []byte                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMessages) Reset() {
	*x = GetGroupMessages{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMessages) ProtoMessage() {}

func (x *GetGroupMessages) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMessages.ProtoReflect.Descriptor instead.
func (*GetGroupMessages) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupMessages) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *GetGroupMessages) GetBefore() []byte {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *GetGroupMessages) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ToChannel     int32                  `protobuf:"varint,2,opt,name=toChannel,proto3" json:"toChannel,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUser) Reset() {
	*x = AddUser{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUser) ProtoMessage() {}

func (x *AddUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUser.ProtoReflect.Descriptor instead.
func (*AddUser) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *AddUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUser) GetToChannel() int32 {
	if x != nil {
		return x.ToChannel
	}
	return 0
}

func (x *AddUser) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type RemoveUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FromChannel   int32                  `protobuf:"varint,2,opt,name=fromChannel,proto3" json:"fromChannel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUser) Reset() {
	*x = RemoveUser{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUser) ProtoMessage() {}

func (x *RemoveUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUser.ProtoReflect.Descriptor instead.
func (*RemoveUser) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RemoveUser) GetFromChannel() int32 {
	if x != nil {
		return x.FromChannel
	}
	return 0
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	LastSeen      uint64                 `protobuf:"varint,2,opt,name=lastSeen,proto3" json:"lastSeen,omitempty"`
	IsOnline      bool                   `protobuf:"varint,3,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`
	ChanId        int32                  `protobuf:"varint,5,opt,name=chanId,proto3" json:"chanId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *GroupMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupMember) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *GroupMember) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *GroupMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMember) GetChanId() int32 {
	if x != nil {
		return x.ChanId
	}
	return 0
}

type GroupChannelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InChannel     int32                  `protobuf:"varint,2,opt,name=inChannel,proto3" json:"inChannel,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	By            string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChannelMessage) Reset() {
	*x = GroupChannelMessage{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChannelMessage) ProtoMessage() {}

func (x *GroupChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChannelMessage.ProtoReflect.Descriptor instead.
func (*GroupChannelMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *GroupChannelMessage) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GroupChannelMessage) GetInChannel() int32 {
	if x != nil {
		return x.InChannel
	}
	return 0
}

func (x *GroupChannelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupChannelMessage) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

type GroupChannelMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*GroupChannelMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupChannelMessages) Reset() {
	*x = GroupChannelMessages{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupChannelMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupChannelMessages) ProtoMessage() {}

func (x *GroupChannelMessages) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupChannelMessages.ProtoReflect.Descriptor instead.
func (*GroupChannelMessages) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *GroupChannelMessages) GetMessages() []*GroupChannelMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GroupMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*GroupMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembers) Reset() {
	*x = GroupMembers{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembers) ProtoMessage() {}

func (x *GroupMembers) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembers.ProtoReflect.Descriptor instead.
func (*GroupMembers) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *GroupMembers) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GroupMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId int32                  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*GroupMessage_AddUser
	//	*GroupMessage_RemoveUser
	//	*GroupMessage_GroupMessage
	//	*GroupMessage_AddChannel
	//	*GroupMessage_DeleteChannel
	Message       isGroupMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessage) Reset() {
	*x = GroupMessage{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessage) ProtoMessage() {}

func (x *GroupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessage.ProtoReflect.Descriptor instead.
func (*GroupMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

func (x *GroupMessage) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMessage) GetMessage() isGroupMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GroupMessage) GetAddUser() *AddUser {
	if x != nil {
		if x, ok := x.Message.(*GroupMessage_AddUser); ok {
			return x.AddUser
		}
	}
	return nil
}

func (x *GroupMessage) GetRemoveUser() *RemoveUser {
	if x != nil {
		if x, ok := x.Message.(*GroupMessage_RemoveUser); ok {
			return x.RemoveUser
		}
	}
	return nil
}

func (x *GroupMessage) GetGroupMessage() *GroupChannelMessage {
	if x != nil {
		if x, ok := x.Message.(*GroupMessage_GroupMessage); ok {
			return x.GroupMessage
		}
	}
	return nil
}

func (x *GroupMessage) GetAddChannel() *GroupChannel {
	if x != nil {
		if x, ok := x.Message.(*GroupMessage_AddChannel); ok {
			return x.AddChannel
		}
	}
	return nil
}

func (x *GroupMessage) GetDeleteChannel() *GroupChannel {
	if x != nil {
		if x, ok := x.Message.(*GroupMessage_DeleteChannel); ok {
			return x.DeleteChannel
		}
	}
	return nil
}

type isGroupMessage_Message interface {
	isGroupMessage_Message()
}

type GroupMessage_AddUser struct {
	AddUser *AddUser `protobuf:"bytes,2,opt,name=addUser,proto3,oneof"`
}

type GroupMessage_RemoveUser struct {
	RemoveUser *RemoveUser `protobuf:"bytes,3,opt,name=removeUser,proto3,oneof"`
}

type GroupMessage_GroupMessage struct {
	GroupMessage *GroupChannelMessage `protobuf:"bytes,4,opt,name=groupMessage,proto3,oneof"`
}

type GroupMessage_AddChannel struct {
	AddChannel *GroupChannel `protobuf:"bytes,5,opt,name=addChannel,proto3,oneof"`
}

type GroupMessage_DeleteChannel struct {
	DeleteChannel *GroupChannel `protobuf:"bytes,6,opt,name=deleteChannel,proto3,oneof"`
}

func (*GroupMessage_AddUser) isGroupMessage_Message() {}

func (*GroupMessage_RemoveUser) isGroupMessage_Message() {}

func (*GroupMessage_GroupMessage) isGroupMessage_Message() {}

func (*GroupMessage_AddChannel) isGroupMessage_Message() {}

func (*GroupMessage_DeleteChannel) isGroupMessage_Message() {}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Request_GetGroupMembers
	//	*Request_GetGroupMessages
	Message       isRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{12}
}

func (x *Request) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetMessage() isRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Request) GetGetGroupMembers() *GetGroupMembers {
	if x != nil {
		if x, ok := x.Message.(*Request_GetGroupMembers); ok {
			return x.GetGroupMembers
		}
	}
	return nil
}

func (x *Request) GetGetGroupMessages() *GetGroupMessages {
	if x != nil {
		if x, ok := x.Message.(*Request_GetGroupMessages); ok {
			return x.GetGroupMessages
		}
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_GetGroupMembers struct {
	GetGroupMembers *GetGroupMembers `protobuf:"bytes,2,opt,name=getGroupMembers,proto3,oneof"`
}

type Request_GetGroupMessages struct {
	GetGroupMessages *GetGroupMessages `protobuf:"bytes,3,opt,name=getGroupMessages,proto3,oneof"`
}

func (*Request_GetGroupMembers) isRequest_Message() {}

func (*Request_GetGroupMessages) isRequest_Message() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*Response_Members
	//	*Response_Messages
	Message       isResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{13}
}

func (x *Response) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetMessage() isResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Response) GetMembers() *GroupMembers {
	if x != nil {
		if x, ok := x.Message.(*Response_Members); ok {
			return x.Members
		}
	}
	return nil
}

func (x *Response) GetMessages() *GroupChannelMessages {
	if x != nil {
		if x, ok := x.Message.(*Response_Messages); ok {
			return x.Messages
		}
	}
	return nil
}

type isResponse_Message interface {
	isResponse_Message()
}

type Response_Members struct {
	Members *GroupMembers `protobuf:"bytes,2,opt,name=members,proto3,oneof"`
}

type Response_Messages struct {
	Messages *GroupChannelMessages `protobuf:"bytes,3,opt,name=messages,proto3,oneof"`
}

func (*Response_Members) isResponse_Message() {}

func (*Response_Messages) isResponse_Message() {}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Request
	//	*ClientMessage_GroupMessage
	//	*ClientMessage_AuthToken
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{14}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ClientMessage) GetGroupMessage() *GroupMessage {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_GroupMessage); ok {
			return x.GroupMessage
		}
	}
	return nil
}

func (x *ClientMessage) GetAuthToken() *AuthenticationToken {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_AuthToken); ok {
			return x.AuthToken
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type ClientMessage_GroupMessage struct {
	GroupMessage *GroupMessage `protobuf:"bytes,3,opt,name=groupMessage,proto3,oneof"`
}

type ClientMessage_AuthToken struct {
	AuthToken *AuthenticationToken `protobuf:"bytes,4,opt,name=authToken,proto3,oneof"`
}

func (*ClientMessage_Request) isClientMessage_Payload() {}

func (*ClientMessage_GroupMessage) isClientMessage_Payload() {}

func (*ClientMessage_AuthToken) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Response
	//	*ServerMessage_GroupMessage
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{15}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ServerMessage) GetGroupMessage() *GroupMessage {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_GroupMessage); ok {
			return x.GroupMessage
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Response struct {
	Response *Response `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type ServerMessage_GroupMessage struct {
	GroupMessage *GroupMessage `protobuf:"bytes,2,opt,name=groupMessage,proto3,oneof"`
}

func (*ServerMessage_Response) isServerMessage_Message() {}

func (*ServerMessage_GroupMessage) isServerMessage_Message() {}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\afirefly\"P\n" +
	"\x10VersionedMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x04R\x02ts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"+\n" +
	"\x13AuthenticationToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"T\n" +
	"\fGroupChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12 \n" +
	"\vchannelType\x18\x03 \x01(\x05R\vchannelType\"/\n" +
	"\x0fGetGroupMembers\x12\x1c\n" +
	"\tchannelId\x18\x01 \x01(\x05R\tchannelId\"_\n" +
	"\x10GetGroupMessages\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x05R\tchannelId\x12\x16\n" +
	"\x06before\x18\x02 \x01(\fR\x06before\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"W\n" +
	"\aAddUser\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\ttoChannel\x18\x02 \x01(\x05R\ttoChannel\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"J\n" +
	"\n" +
	"RemoveUser\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\vfromChannel\x18\x02 \x01(\x05R\vfromChannel\"\x8d\x01\n" +
	"\vGroupMember\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\blastSeen\x18\x02 \x01(\x04R\blastSeen\x12\x1a\n" +
	"\bisOnline\x18\x03 \x01(\bR\bisOnline\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12\x16\n" +
	"\x06chanId\x18\x05 \x01(\x05R\x06chanId\"m\n" +
	"\x13GroupChannelMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tinChannel\x18\x02 \x01(\x05R\tinChannel\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\"P\n" +
	"\x14GroupChannelMessages\x128\n" +
	"\bmessages\x18\x01 \x03(\v2\x1c.firefly.GroupChannelMessageR\bmessages\">\n" +
	"\fGroupMembers\x12.\n" +
	"\amembers\x18\x01 \x03(\v2\x14.firefly.GroupMemberR\amembers\"\xd4\x02\n" +
	"\fGroupMessage\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x05R\agroupId\x12,\n" +
	"\aaddUser\x18\x02 \x01(\v2\x10.firefly.AddUserH\x00R\aaddUser\x125\n" +
	"\n" +
	"removeUser\x18\x03 \x01(\v2\x13.firefly.RemoveUserH\x00R\n" +
	"removeUser\x12B\n" +
	"\fgroupMessage\x18\x04 \x01(\v2\x1c.firefly.GroupChannelMessageH\x00R\fgroupMessage\x127\n" +
	"\n" +
	"addChannel\x18\x05 \x01(\v2\x15.firefly.GroupChannelH\x00R\n" +
	"addChannel\x12=\n" +
	"\rdeleteChannel\x18\x06 \x01(\v2\x15.firefly.GroupChannelH\x00R\rdeleteChannelB\t\n" +
	"\amessage\"\xb3\x01\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12D\n" +
	"\x0fgetGroupMembers\x18\x02 \x01(\v2\x18.firefly.GetGroupMembersH\x00R\x0fgetGroupMembers\x12G\n" +
	"\x10getGroupMessages\x18\x03 \x01(\v2\x19.firefly.GetGroupMessagesH\x00R\x10getGroupMessagesB\t\n" +
	"\amessage\"\x95\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x121\n" +
	"\amembers\x18\x02 \x01(\v2\x15.firefly.GroupMembersH\x00R\amembers\x12;\n" +
	"\bmessages\x18\x03 \x01(\v2\x1d.firefly.GroupChannelMessagesH\x00R\bmessagesB\t\n" +
	"\amessage\"\xc3\x01\n" +
	"\rClientMessage\x12,\n" +
	"\arequest\x18\x02 \x01(\v2\x10.firefly.RequestH\x00R\arequest\x12;\n" +
	"\fgroupMessage\x18\x03 \x01(\v2\x15.firefly.GroupMessageH\x00R\fgroupMessage\x12<\n" +
	"\tauthToken\x18\x04 \x01(\v2\x1c.firefly.AuthenticationTokenH\x00R\tauthTokenB\t\n" +
	"\apayload\"\x88\x01\n" +
	"\rServerMessage\x12/\n" +
	"\bresponse\x18\x01 \x01(\v2\x11.firefly.ResponseH\x00R\bresponse\x12;\n" +
	"\fgroupMessage\x18\x02 \x01(\v2\x15.firefly.GroupMessageH\x00R\fgroupMessageB\t\n" +
	"\amessageB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_message_proto_goTypes = []any{
	(*VersionedMessage)(nil),     // 0: firefly.VersionedMessage
	(*AuthenticationToken)(nil),  // 1: firefly.AuthenticationToken
	(*GroupChannel)(nil),         // 2: firefly.GroupChannel
	(*GetGroupMembers)(nil),      // 3: firefly.GetGroupMembers
	(*GetGroupMessages)(nil),     // 4: firefly.GetGroupMessages
	(*AddUser)(nil),              // 5: firefly.AddUser
	(*RemoveUser)(nil),           // 6: firefly.RemoveUser
	(*GroupMember)(nil),          // 7: firefly.GroupMember
	(*GroupChannelMessage)(nil),  // 8: firefly.GroupChannelMessage
	(*GroupChannelMessages)(nil), // 9: firefly.GroupChannelMessages
	(*GroupMembers)(nil),         // 10: firefly.GroupMembers
	(*GroupMessage)(nil),         // 11: firefly.GroupMessage
	(*Request)(nil),              // 12: firefly.Request
	(*Response)(nil),             // 13: firefly.Response
	(*ClientMessage)(nil),        // 14: firefly.ClientMessage
	(*ServerMessage)(nil),        // 15: firefly.ServerMessage
}
var file_message_proto_depIdxs = []int32{
	8,  // 0: firefly.GroupChannelMessages.messages:type_name -> firefly.GroupChannelMessage
	7,  // 1: firefly.GroupMembers.members:type_name -> firefly.GroupMember
	5,  // 2: firefly.GroupMessage.addUser:type_name -> firefly.AddUser
	6,  // 3: firefly.GroupMessage.removeUser:type_name -> firefly.RemoveUser
	8,  // 4: firefly.GroupMessage.groupMessage:type_name -> firefly.GroupChannelMessage
	2,  // 5: firefly.GroupMessage.addChannel:type_name -> firefly.GroupChannel
	2,  // 6: firefly.GroupMessage.deleteChannel:type_name -> firefly.GroupChannel
	3,  // 7: firefly.Request.getGroupMembers:type_name -> firefly.GetGroupMembers
	4,  // 8: firefly.Request.getGroupMessages:type_name -> firefly.GetGroupMessages
	10, // 9: firefly.Response.members:type_name -> firefly.GroupMembers
	9,  // 10: firefly.Response.messages:type_name -> firefly.GroupChannelMessages
	12, // 11: firefly.ClientMessage.request:type_name -> firefly.Request
	11, // 12: firefly.ClientMessage.groupMessage:type_name -> firefly.GroupMessage
	1,  // 13: firefly.ClientMessage.authToken:type_name -> firefly.AuthenticationToken
	13, // 14: firefly.ServerMessage.response:type_name -> firefly.Response
	11, // 15: firefly.ServerMessage.groupMessage:type_name -> firefly.GroupMessage
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[11].OneofWrappers = []any{
		(*GroupMessage_AddUser)(nil),
		(*GroupMessage_RemoveUser)(nil),
		(*GroupMessage_GroupMessage)(nil),
		(*GroupMessage_AddChannel)(nil),
		(*GroupMessage_DeleteChannel)(nil),
	}
	file_message_proto_msgTypes[12].OneofWrappers = []any{
		(*Request_GetGroupMembers)(nil),
		(*Request_GetGroupMessages)(nil),
	}
	file_message_proto_msgTypes[13].OneofWrappers = []any{
		(*Response_Members)(nil),
		(*Response_Messages)(nil),
	}
	file_message_proto_msgTypes[14].OneofWrappers = []any{
		(*ClientMessage_Request)(nil),
		(*ClientMessage_GroupMessage)(nil),
		(*ClientMessage_AuthToken)(nil),
	}
	file_message_proto_msgTypes[15].OneofWrappers = []any{
		(*ServerMessage_Response)(nil),
		(*ServerMessage_GroupMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
